// Generated by CoffeeScript 1.6.2
(function() {
  var Inject;

  Inject = (function() {
    function Inject() {}

    return Inject;

  })();

  Inject.prototype.get_connected_url = function() {
    return $('.acceuil_btn a:first').attr('href');
  };

  Inject.prototype.get_ident_div = function() {
    return $('#ident_div_ident');
  };

  Inject.prototype.enter_credentials = function(login, password) {
    $('input[type="password"][name="pwd_abo"]').val(password);
    $('#ident_div_ident img[src^="chiffre.php"]').each(function() {
      return console.log($(this).attr('src'));
    });
    return 42;
  };

  module.exports = Inject;

}).call(this);
