// Generated by CoffeeScript 1.6.2
(function() {
  var fs;

  fs = require('fs');

  module.exports.save_dataURL_to_file = function(dataURL, filename) {
    var buf, data;

    data = dataURL.replace(/^data:image\/\w+;base64,/, "");
    buf = new Buffer(data, 'base64');
    return fs.writeFile(filename, buf);
  };

}).call(this);
