// Generated by CoffeeScript 1.6.2
(function() {
  var FreeMobile, client, debug;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  debug = require('debug')('freemobile:examples:login');

  FreeMobile = require('..');

  client = new FreeMobile({
    verbose: true,
    browser: {
      verbose: true
    },
    login: process.argv[2],
    password: process.argv[3]
  });

  client.on('ready', function() {
    debug('ready OK');
    return client.login(function() {
      return debug('login OK');
    });
  });

  client.on('logged', function() {
    return debug('logged');
  });

}).call(this);
